require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/returns", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # Return. As you add validations to Return, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      Return.create! valid_attributes
      get returns_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      return = Return.create! valid_attributes
      get return_url(return)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_return_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      return = Return.create! valid_attributes
      get edit_return_url(return)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Return" do
        expect {
          post returns_url, params: { return: valid_attributes }
        }.to change(Return, :count).by(1)
      end

      it "redirects to the created return" do
        post returns_url, params: { return: valid_attributes }
        expect(response).to redirect_to(return_url(Return.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Return" do
        expect {
          post returns_url, params: { return: invalid_attributes }
        }.to change(Return, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post returns_url, params: { return: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested return" do
        return = Return.create! valid_attributes
        patch return_url(return), params: { return: new_attributes }
        return.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the return" do
        return = Return.create! valid_attributes
        patch return_url(return), params: { return: new_attributes }
        return.reload
        expect(response).to redirect_to(return_url(return))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        return = Return.create! valid_attributes
        patch return_url(return), params: { return: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested return" do
      return = Return.create! valid_attributes
      expect {
        delete return_url(return)
      }.to change(Return, :count).by(-1)
    end

    it "redirects to the returns list" do
      return = Return.create! valid_attributes
      delete return_url(return)
      expect(response).to redirect_to(returns_url)
    end
  end
end
