require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/tv_sizes", type: :request do
  
  # This should return the minimal set of attributes required to create a valid
  # TvSize. As you add validations to TvSize, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  describe "GET /index" do
    it "renders a successful response" do
      TvSize.create! valid_attributes
      get tv_sizes_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      tv_size = TvSize.create! valid_attributes
      get tv_size_url(tv_size)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_tv_size_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      tv_size = TvSize.create! valid_attributes
      get edit_tv_size_url(tv_size)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new TvSize" do
        expect {
          post tv_sizes_url, params: { tv_size: valid_attributes }
        }.to change(TvSize, :count).by(1)
      end

      it "redirects to the created tv_size" do
        post tv_sizes_url, params: { tv_size: valid_attributes }
        expect(response).to redirect_to(tv_size_url(TvSize.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new TvSize" do
        expect {
          post tv_sizes_url, params: { tv_size: invalid_attributes }
        }.to change(TvSize, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post tv_sizes_url, params: { tv_size: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested tv_size" do
        tv_size = TvSize.create! valid_attributes
        patch tv_size_url(tv_size), params: { tv_size: new_attributes }
        tv_size.reload
        skip("Add assertions for updated state")
      end

      it "redirects to the tv_size" do
        tv_size = TvSize.create! valid_attributes
        patch tv_size_url(tv_size), params: { tv_size: new_attributes }
        tv_size.reload
        expect(response).to redirect_to(tv_size_url(tv_size))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        tv_size = TvSize.create! valid_attributes
        patch tv_size_url(tv_size), params: { tv_size: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_content)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested tv_size" do
      tv_size = TvSize.create! valid_attributes
      expect {
        delete tv_size_url(tv_size)
      }.to change(TvSize, :count).by(-1)
    end

    it "redirects to the tv_sizes list" do
      tv_size = TvSize.create! valid_attributes
      delete tv_size_url(tv_size)
      expect(response).to redirect_to(tv_sizes_url)
    end
  end
end
